baseURL: https://www.internozero.it
languageCode: it
title: Qui puoi semplicemente lavorare!

theme: 'hugo-fresh'

googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
disableKinds:
- taxonomy
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
 
params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/internozero1.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 500
    # height: 228
  font:
    name: "Open Sans"
    sizes: [400,400]
  hero:
    # Main hero title
    title: Qui puoi semplicemente lavorare!
    # Hero subtitle (optional)
    subtitle: 'Lo spazio DEDICATO al Co-Working, a Campi Bisenzio' 
    subsubtitle: 
      - A 100 metri dalla fermata del BUS e 150 metri dalla Coop di via Palagetta
    # Button text
    buttontext: Prenota Subito!
    buttontext2: ..Dove e Come..
    # Where the main hero button links to
    buttonlink: "#section6"
    buttonlink2: "#section2a"
    # Hero images for carousel (from static/images/gallery/_____)
    # Urls and image names are inside the hero-body template because it is javascript

    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    clientlogos:
    - logo: repetitiveit
      url: https://www.repetitive.it
    - logo: powerupstudio
      url: https://www.powerupstudio.it
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Newsletter
    url: "#section2"  
  - title: Ingressi
    url: "#section1"
  - title: Prenota
    url: "#section6"
  - title: Perché InternoZer0?
    url: "#section2a"
  - title: Contatti
    url: "#section5"
  section1:
    title: Ingressi @InternoZer0
    subtitle:
    tiles:
    - title: Giornaliero da 15€
      icon: hours-9
      text: 9:00-18:00
      url: "#section12"
      buttonText: Confronta gli ingressi
    - title: Settimanale da 70€
      icon: calendar-week
      text: Da Lunedì a Venerdì
      url: "#section12"
      buttonText: Confronta gli ingressi
    - title: Mensile da 250€
      icon: calendar-month
      text: 4 Settimane, Lun-Ven
      url: "#section12"
      buttonText: Confronta gli ingressi
  section12:
    title: Confronta e Prenota
    subtitle:
    tiles:
    - title: Giornaliero da 15€
      icon: hours-9
      list:
      - "- Dalle 9:00 alle 18:00"
      - "- Carnet di ingressi da usare in 2, 3 o 4 mesi"
      - "- Possibile prenotare (bassa priorità)"
      url: "#section6"
      buttonText: "Prenota Ora!"
    - title: Settimanale da 70€
      icon: calendar-week
      list:
      - "- 5 giorni consecutivi (Lun-Ven)"
      - "- Scrivania prenotabile (media priorità)"
      - "- 10% di sconto su attività organizzate da InternoZer0 (Posto garantito)"
      url: "#section6"
      buttonText: "Prenota Ora!"
    - title: Mensile da 250€
      icon: calendar-month
      list:
      - "- 4 settimane consecutive (Lun-Ven)"
      - "- Scrivania prenotabile (alta priorità)"
      - "- 25% di sconto su attività organizzate da InternoZer0 (Posto garantito)"
      url: "#section6"
      buttonText: "Prenota Ora!"
  section2:
    title: Resta Connesso!
    title2: Iscriviti alla Newsletter...
    subtitle: ...per ricevere aggiornamenti su attività ed eventi!
    buttonText: "Eventi esclusivi ti aspettano!"
  section2a:
    title2a: "Perché scegliere InternoZer0? Riassunto in 3 Parole:"
    subtitle2a: Compatto, Connesso, Confortevole
    text2a: 
      - "InternoZer0 è uno spazio di Co-Working limitato a 8 postazioni di lavoro, per garantire un ambiente tranquillo e confortevole."
      - "Lo spazio di Co-Working si trova nella parte sud di Campi Bisenzio a 100 metri dalla fermata del BUS in via Palagetta e 150 metri dal supermercato Coop; una location perfetta dove trovare facillmente parcheggio ed a non più di 2 minuti a piedi da supermercato, bar, ristorante oppure da un trancio di pizza da mangiare passeggiando."
      - "### Da InternoZer0 Inoltre Trovi:"
      - "- WI-FI 5G connesso a Fibra FTTH"
      - "- Riscaldamento/aria condizionata"
      - "- Mini-Cucina con: acqua potabile, minifrigo, bollitore, macchinetta del caffè a cialde"
  section5:
    title: Vuoi sapere come funziona InternoZer0?
    subtitle: Contattaci, vieni a trovarci, scopri il nostro spazio!
    buttonText: Send Message
    action: https://formspree.io/f/meogevzz
    method: POST
  section6:
    title: Prenota una scrivania
    subtitle: Seleziona il tipo di ingresso ed il quando, poi ti richiamiamo noi!
    buttonText: Send Message
    action: https://formspree.io/f/meogevzz
    method: POST
  footer:
    # Logo (from static/images/logos/___)
    logo: internozero1.svg
    # Social Media Title
#    socialmediatitle: Follow Us
#    # Social media links (GitHub, Twitter, etc.). All are optional.
#    socialmedia:
#    - link: https://github.com/#
#      # Icons are from Font Awesome
#      icon: github
#    - link: https://dribbble.com/#
#      icon: dribbble
#    - link: https://facebook.com/#
#      icon: facebook
#    - link: https://twitter.com/
#      icon: twitter
#    - link: https://bitbucket.org/#
#      icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "Dove ci troviamo"
        links:
        - text: Via del Melograno, angolo con via delle Betulle, 5013 Campi Bisenzio (FI)
          link: https://maps.app.goo.gl/owLasgSvYsaU3xMd8
#          link: /
#        - text: Why choose our product?
#          link: /
#        - text: Compare features
#          link: /
#        - text: Our roadmap
#          link: /
#        - text: AGB
#          link: /agb
#      column2:
#        title: "Docs"
#        links:
#        - text: Get started
#          link: /
#        - text: User guides
#          link: /
#        - text: Admin guide
#          link: /
#        - text: Developers
#          link: /
      column3:
        title: "Website by"
        links:
        - text: Repetitive IT
          link: https://www.repetitive.it
#        - text: Tech articles
#          link: /blog/second
