baseURL: https://www.internozero.it
languageCode: it
title: Qui puoi semplicemente lavorare!

theme: 'hugo-fresh'

googleAnalytics: # Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
# Disables warnings
disableKinds:
- taxonomy
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
 
params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/internozero1.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 500
    # height: 228
  font:
    name: "Open Sans"
    sizes: [400,400]
  hero:
    # Main hero title
    title: Qui puoi semplicemente lavorare!
    # Hero subtitle (optional)
    subtitle: Lo spazio DEDICATO al Co-Working a Campi Bisenzio (FI).
    subsubtitle: 
      - Da noi troverai Wi-Fi con conconnessione FTTH ed Aria Condizionata
    # Button text
    buttontext: Prenota Subito!
    # Where the main hero button links to
    buttonlink: "#section5"
    # Hero image (from static/images/___)
    image: illustrations/fullLogo.svg
    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
    clientlogos:
    - logo: repetitiveit
      url: https://www.repetitive.it
#      name: Repetitive IT
    - logo: powerupstudio
      url: https://www.powerupstudio.it
#    - logo: kromo
#      url: https://github.com/StefMa/hugo-fresh
#    - logo: infinite
#      url: https://hugo-fresh.vercel.app/
#    - logo: gutwork
#      url: https://bulma.io/
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Ingressi
    url: "#section1"
  - title: Contatti
    url: "#section5"
# - title: Log in
#    url: /
#  - title: Sign up
#    url: /
#    button: true
#  section1:
#    title: Cosa Trovi Da Noi
#    subtitle:
#    tiles:
#    - title: Scrivanie Mobili e Fiibra Ottica
#      icon: plug-cloud
#      text: Per farti lavorare in Locale e Remoto
#    - title: Acqua, Caffè e Thè
#      icon: mouse-globe
#      text: Per non lasciarti a secco
#    - title: Stampante/Climatizzatore/Frigorifero
#      icon: laptop-cloud
#      text: Per darti il massimo del comfort
  section1:
    title: Ingressi @InternoZer0
    subtitle:
    tiles:
    - title: Giornaliero da 15€
      icon: hours-24
      text: Dalle 9:00 alle 18:00
      url: https://www.internozero.it/section12
      buttonText: Confronta e Prenota
    - title: Settimanale da 70€
      icon: calendar-week
      text: Da Lun. a Ven. - 9 to 18
      url: https://www.internozero.it/section12
      buttonText: Confronta e Prenota
    - title: Mensile da 250€
      icon: calendar-month
      text: 4 Settimane, dal Lun. a Ven.
      url: "#section12"
      buttonText: Confronta e Prenota
  section12:
    title: Confronta e Prenota
    subtitle:
    tiles:
    - title: Giornaliero da 15€
      icon: hours-24
      list:
      - "- Acqua del Sindaco"
      - "- Macchinetta del caffè"
      - "- Bollitore"
      - "- Disponibile dal Lunedì al Venerdì"
      - "- Orario 9:00 - 18:00"
      - "- Pagamento all'ingresso"
      - "- Scrivania prenotabile (bassa priorità)"
      url: https://www.internozero.it/prenota
      buttonText: "Prenota Ora!"
    - title: Settimanale da 70€
      icon: calendar-week
      list:
      - "- Acqua del Sindaco"
      - "- Macchinetta del caffè"
      - "- Bollitore"
      - "- Disponibile dal Lunedì al Venerdì"
      - "- Orario 9:00 - 18:00"
      - "- Pagamento primo giorno dell'abbonamento (Ricorsivo)"
      - "- Scrivania prenotabile (media priorità)"
      - "- 25% di sconto su attività organizzate da InternoZer0 (Posto garantito)"
      - "- 10% di sconto su attività organizzate da terzi (Posto non garantito)"
      url: https://www.internozero.it/prenota
      buttonText: "Prenota Ora!"
    - title: Mensile da 250€
      icon: calendar-month
      list:
      - "- Acqua del Sindaco"
      - "- Macchinetta del caffè"
      - "- Bollitore"
      - "- Disponibile dal Lunedì al Venerdì"
      - "- Orario 9:00 - 18:00"
      - "- Pagamento primo giorno dell'abbonamento"
      - "- Scrivania prenotabile (alta priorità)"
      - "- 50% di sconto su attività organizzate da InternoZer0 (Posto garantito)"
      - "- 20% di sconto su attività organizzate da terzi (Posto non garantito)"  
      url: https://www.internozero.it/prenota
      buttonText: "Prenota Ora!"
#  section2:
#    title: You're here because you want the best
#    subtitle: And we know it
#    features:
#    - title: Powerful and unified interface
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      # Icon (from static/images/illustrations/icons/___.svg)
#      icon: laptop-globe
#    - title: Cross-device synchronisation
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      icon: doc-sync
#    - title: Nomad system
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      icon: mobile-feed
#  section3:
#    title: One platform
#    subtitle: To rule them all
#    image: illustrations/mockups/app-mockup.png
#    buttonText: Get started
#    buttonLink: "#"
#  section4:
#    title: Our Clients love us!
#    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
#    clients:
#    - name: Irma Walters
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Accountant
#      img: 1
#    - name: John Bradley
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Financial Analyst
#      img: 2
#    - name: Gary Blackman
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: HR Manager
#      img: 3
  section5:
    title: Vuoi sapere come funziona Interno Zer0?
    subtitle: Contattaci, vieni a trovarci e scopri il nostro spazio!
    buttonText: Send Message
    action: https://formspree.io/f/meogevzz
    method: POST
  footer:
    # Logo (from static/images/logos/___)
    logo: internozero1.svg
    # Social Media Title
#    socialmediatitle: Follow Us
#    # Social media links (GitHub, Twitter, etc.). All are optional.
#    socialmedia:
#    - link: https://github.com/#
#      # Icons are from Font Awesome
#      icon: github
#    - link: https://dribbble.com/#
#      icon: dribbble
#    - link: https://facebook.com/#
#      icon: facebook
#    - link: https://twitter.com/
#      icon: twitter
#    - link: https://bitbucket.org/#
#      icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "Dove ci troviamo"
        links:
        - text: Via del Melograno, angolo con via delle Betulle, 5013 Campi Bisenzio (FI)
          link: https://maps.app.goo.gl/owLasgSvYsaU3xMd8
#          link: /
#        - text: Why choose our product?
#          link: /
#        - text: Compare features
#          link: /
#        - text: Our roadmap
#          link: /
#        - text: AGB
#          link: /agb
#      column2:
#        title: "Docs"
#        links:
#        - text: Get started
#          link: /
#        - text: User guides
#          link: /
#        - text: Admin guide
#          link: /
#        - text: Developers
#          link: /
      column3:
        title: "Website by"
        links:
        - text: Repetitive IT
          link: https://www.repetitive.it
#        - text: Tech articles
#          link: /blog/second
