baseURL: https://www.internozero.it
languageCode: it
title: Senza classi! Senza orari! Il tuo inglese al lavoro!

theme: 'hugo-fresh'
# Enable robots.txt generation
enableRobotsTXT: true
# Put in your tracking code without quotes like this: UA-XXX for universal tracking or G-XXX analytics v4 tracking
googleAnalytics: AW-17075018039
# Disables warnings
disableKinds:
- taxonomy
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
 
params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/internozero1.svg
    link: /
    # Default width/height. Uncomment if you need to change
    # width: 500
    # height: 228
  font:
    name: "Open Sans"
    sizes: [400,400]
  hero:
    # Hero background image (from static/images/_____)
    image: gallery/campocorto.jpg
    # Main hero title
    title:  The Full English Immersion Hub
    # Hero subtitle (optional)
    subtitle: Non studiare l'inglese, lavoraci dentro!
    # Hero subsubtitle (optional)
    subsubtitle: 
      - A 100 metri dalla fermata del BUS e 150 metri dalla Coop di via Palagetta
    # Button text
    buttontext: Scopri
    buttonlink: "#section2a"
    # Second button text
    buttontext2: Confronta
    buttonlink2: "#section12"
    # Third button text
    buttontext3: Prenota
    buttonlink3: "#section6"
    # Hero images for carousel (from static/images/gallery/_____)
    # Urls and image names are inside the hero-body template because it is javascript

    # Footer logos (from static/images/logos/clients/*.svg)
    # urls are optional
  #  clientlogos:
  #  - logo: repetitiveit
  #    url: https://www.repetitive.it
  #  - logo: powerupstudio
  #    url: https://www.powerupstudio.it
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  #- title: "Classi e Training"
  #  url: "/indicecorsi/"
  #- title: Newsletter
  #  url: "/#section2"  
  - title: Ingressi
    url: "/#section12"
  - title: Prenota
    url: "/#section6"
  - title: Perché InternoZero?
    url: "/#section2a"
  - title: Contatti
    url: "/#section5"
  - title: F.A.Q.
    url: "/faq/"
  section1:
    title: Ingressi @InternoZero
    subtitle:
    tiles:
    - title: Giornaliero da 40€ + IVA
      icon: hours-9
      text: 9:00-18:00
      text1: Nominale
      url: "#section12"
      buttonText: Confronta gli ingressi
    - title: Settimanale da 160€ + IVA
      icon: calendar-week
      text: Da Lunedì a Venerdì
      text1: Nominale da inizio settimana
      url: "#section12"
      buttonText: Confronta gli ingressi
    - title: Mensile da 500€ + IVA
      icon: calendar-month
      text: 4 Settimane, Lun-Ven
      text1: Trasferibile
      url: "#section12"
      buttonText: Confronta gli ingressi
  section12:
    title: Ingressi @InternoZero
    subtitle:
    tiles:
    - title: Giornaliero da 40€ + IVA
      icon: hours-9
      list:
      - "- Dalle 9:00 alle 18:00"
      - "- Acquista uno o più ingressi giornalieri da usare quando vuoi"
      - "- Postazione: if you fit, you sit! (Posto non garantito)"
      - "- Ingressi Nominali: 1 ingresso a persona, non trasferibile"
      url: "#section6"
      buttonText: "Prenota Ora!"
    - title: Settimanale da 160€ + IVA
      icon: calendar-week
      list:
      - "- 5 giorni consecutivi (Lun-Ven)"
      - "- Postazione: booked 4 the Week!"
      - "- 1 ingresso giornaliero extra da usare con chi vuoi e quando vuoi"
      - "- Ingressi parzialmente nominali per aziende: 1 dipendente a settimana"
      url: "#section6"
      buttonText: "Prenota Ora!"
    - title: Mensile da 500€ + IVA 
      icon: calendar-month
      list:
      - "- 4 settimane consecutive (Lun-Ven)"
      - "- Postazione: booked 4 the Month!"
      - "- 1 ingresso giornaliero extra a settimana da usare con chi vuoie quando vuoi"
      - "- Ingressi flessibili: manda i tuoi dipendenti quando vuoi, senza vincoli di giorni"
      url: "#section6"
      buttonText: "Prenota Ora!"
  section2:
    title: Resta Connesso!
    title2: Iscriviti alla Newsletter...
    subtitle: ...per ricevere aggiornamenti su attività ed eventi!
    buttonText: "Eventi esclusivi ti aspettano!"
  section2a:
    title2a: "Entra in un Augmented Office!"
    subtitle2a: E impara mentre resti produttivo!
    text2a: 
      - "**Internozero è il primo Full English Immersion Hub dove professionisti e manager di diverse aziende lavorano affiancati in un ambiente 100% English-speaking.**"
      - " - **Lezioni Destrutturate:** vivremo in scenari realistici, parleremo di progetti, email, presentazioni e di 'Water Cooler Talk.' Niente lezioni tradizionali e niente compiti a casa!"
      - " - **Parlare Corporate:** impara a riconoscere le sfumature e le espressioni usate durante le riunioni e negli uffici internazionali."
      - " - **Acquisisci Sicurezza:**  -*Per parlare bene inglese devi andare in Inghilterra!*- Dicevano... Con InternoZero puoi farlo senza muoverti dalla provincia di Firenze!"
      - " - **Feedback Istantaneo:** grazie ai tutor sempre in ufficio per darti un feedback su errori di pronuncia, grammatica, ed aiutarti ad arricchire il tuo vocabolario."
      - " - **Batti L'Ansia:** durante i Daily Corporate Touchpoint e con lo 1-on-1 Daily Corporate Coffee comincia a parlare Inglese in pubblico."
  section5:
    title: Vuoi sapere come funziona InternoZero?
    subtitle: Contattaci, vieni a trovarci, scopri il nostro spazio!
    buttonText: Send Message
    action: https://formspree.io/f/meogevzz
    method: POST
  section6:
    title: Comincia Subito!
    subtitle: Seleziona il tipo di ingresso e quando vorresti cominciare, poi ti richiamiamo noi!
    buttonText: Send Message
    action: https://formspree.io/f/mnnddlvz
    method: POST
  footer:
    # Logo (from static/images/logos/___)
    logo: internozero1.svg
    # Social Media Title
#    socialmediatitle: Follow Us
#    # Social media links (GitHub, Twitter, etc.). All are optional.
#    socialmedia:
#    - link: https://github.com/#
#      # Icons are from Font Awesome
#      icon: github
#    - link: https://dribbble.com/#
#      icon: dribbble
#    - link: https://facebook.com/#
#      icon: facebook
#    - link: https://twitter.com/
#      icon: twitter
#    - link: https://bitbucket.org/#
#      icon: bitbucket
    bulmalogo: false
    quicklinks:
      column1:
        title: "Dove Siamo"
        links:
        - text: Via del Melograno 12, a Campi B.zio (FI)
          link: https://maps.app.goo.gl/dWMzqS9FGsqSFCTf6
        - text: Privacy Policy
          link: /privacy
#        - text: Compare features
#          link: /
#        - text: Our roadmap
#          link: /
#        - text: AGB
#          link: /agb
#      column2:
#        title: "Docs"
#        links:
#        - text: Get started
#          link: /
#        - text: User guides
#          link: /
#        - text: Admin guide
#          link: /
#        - text: Developers
#          link: /
#      column3:
#        title: "Website by"
#        links:
#        - text: Repetitive IT
#          link: https://www.repetitive.it
#        - text: Tech articles
#          link: /blog/second
